title: Stefania Mattioni
description: Personal website of Stefania Mattioni · Projects and CV
url: https://stemat9787.github.io
baseurl: ""

academicons: true
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default


author:
  name: Stefania Mattioni
  email: stefania.mattioni@ugent.be
  avatar: /assets/images/avatar.jpg
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SteMat9787"
    - label: "Google Scholar"
   #   icon: "ai ai-google-scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=dD6BUzYAAAAJ"
    - label: "ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/0000-0001-8279-6118"
   # - label: "Email"
   #   icon: "fas fa-envelope"
   #   url: "mailto:stefania.mattioni87@gmail.com"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Show author profile on all pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true     # <- shows the date on teasers and post pages
      read_time: true
      comments: false
      share: false
      toc: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
