title: Stefania Mattioni
description: Personal website of Stefania Mattioni · Projects and CV
url: https://SteMat9787.github.io
author:
  name: Stefania Mattioni
  email: stefania.mattioni87@gmail.com
  avatar: /assets/images/avatar.jpg
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SteMat9787"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=dD6BUzYAAAAJ&hl=fr

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      toc: true
