title: Stefania Mattioni
description: Portfolio · Blog · CV · Projects
url: https://SteMat9787.github.io
author:
  name: Stefania Mattioni
  email: stefania.mattioni87@gmail.com
  avatar: docs/assets/images/avatar.jpg

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: false
      share: false
      toc: true
