title: Stefania Mattioni
description: Personal website of Stefania Mattioni · Projects and CV
url: https://stemat9787.github.io
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
academicons: true

author:
  name: Stefania Mattioni
  email: stefania.mattioni87@gmail.com
  avatar: /assets/images/avatar.jpg
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SteMat9787"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=dD6BUzYAAAAJ"
   # - label: "Email"
   #   icon: "fas fa-envelope"
   #   url: "mailto:stefania.mattioni87@gmail.com"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Show author profile on all pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
